{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tyk-sre-assignment-app.serviceAccountName" . }}
  namespace: {{ include "tyk-sre-assignment-app.namespace" . }}
  labels:
    {{- include "tyk-sre-assignment-app.labels" . | nindent 4 }}
{{- end }}